//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPMonitoring.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FtpMonitoringEntities : DbContext
    {
        public FtpMonitoringEntities()
            : base("name=FtpMonitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HistoryMonitoringLog> HistoryMonitoringLogs { get; set; }
        public virtual DbSet<MasterBatchFile> MasterBatchFiles { get; set; }
        public virtual DbSet<MasterFile> MasterFiles { get; set; }
        public virtual DbSet<MasterPath> MasterPaths { get; set; }
        public virtual DbSet<MasterPatternExtension> MasterPatternExtensions { get; set; }
        public virtual DbSet<MasterSRO> MasterSROes { get; set; }
        public virtual DbSet<MasterStatu> MasterStatus { get; set; }
        public virtual DbSet<MonitoringConfiguration> MonitoringConfigurations { get; set; }
        public virtual DbSet<MonitoringLogDetail> MonitoringLogDetails { get; set; }
        public virtual DbSet<MonitoringLog> MonitoringLogs { get; set; }
    
        public virtual ObjectResult<spListHistoryMonitoringLogs_Result> spListHistoryMonitoringLogs(Nullable<int> fileId)
        {
            var fileIdParameter = fileId.HasValue ?
                new ObjectParameter("fileId", fileId) :
                new ObjectParameter("fileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListHistoryMonitoringLogs_Result>("spListHistoryMonitoringLogs", fileIdParameter);
        }
    }
}
