//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryMonitoringLog
    {
        public int Id { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> MonitoringLogDate { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> FileModifiedDatetime { get; set; }
        public Nullable<System.DateTime> ETLRunDatetime { get; set; }
    
        public virtual MasterFile MasterFile { get; set; }
        public virtual MasterStatu MasterStatu { get; set; }
    }
}
