//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTPMonitoring.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterStatu()
        {
            this.HistoryMonitoringLogs = new HashSet<HistoryMonitoringLog>();
            this.MonitoringConfigurations = new HashSet<MonitoringConfiguration>();
            this.MonitoringLogDetails = new HashSet<MonitoringLogDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PatternExtensionId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryMonitoringLog> HistoryMonitoringLogs { get; set; }
        public virtual MasterPatternExtension MasterPatternExtension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoringConfiguration> MonitoringConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitoringLogDetail> MonitoringLogDetails { get; set; }
    }
}
